version: '3'

services:
  app:
    container_name: arduino-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1090:1090"
    volumes:
      - "./database:/build/database"